# Generated by Django 2.0.3 on 2018-10-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmeasuringunit',
            name='measuring_unit',
            field=models.CharField(max_length=32),
        ),
    ]
