# Generated by Django 2.0.3 on 2018-10-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20181018_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmeasuringunit',
            name='base_measuring_unit',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='productmeasuringunit',
            name='measuring_unit',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
