# Generated by Django 2.0.3 on 2018-10-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20181018_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transporter',
            old_name='capacity',
            new_name='max_capacity',
        ),
        migrations.AddField(
            model_name='transporter',
            name='minimum_capacity',
            field=models.FloatField(default=100.0),
            preserve_default=False,
        ),
    ]
