# Generated by Django 2.0.3 on 2018-11-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20181110_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item_picture',
            field=models.ImageField(upload_to='D:\\hobbyproject\\superfarmer\\uploaded_pictures'),
        ),
    ]
