# Generated by Django 2.0.3 on 2018-10-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20181018_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporter',
            name='max_capacity',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='minimum_capacity',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
    ]
