# Generated by Django 2.0.3 on 2018-10-19 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20181018_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorygroundnutattributes',
            name='inventory_item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Product'),
        ),
    ]
