# Generated by Django 2.0.3 on 2018-10-19 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20181019_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety_name', models.CharField(max_length=24, unique=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='inventorygroundnutattributes',
            name='inventory_item_id',
        ),
        migrations.DeleteModel(
            name='InventoryGroundnutAttributes',
        ),
    ]
