# Generated by Django 2.0.3 on 2018-11-17 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20181116_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='seller_id',
            new_name='seller',
        ),
        migrations.AlterUniqueTogether(
            name='seller',
            unique_together={('seller', 'sells')},
        ),
    ]
