# Generated by Django 2.0.3 on 2018-10-19 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20181019_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattributes',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='ProductAttributes',
        ),
    ]
