# Generated by Django 2.0.3 on 2018-10-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20181019_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='registration_status',
            field=models.CharField(default='unregistered', max_length=32),
        ),
    ]
