# Generated by Django 2.0.3 on 2019-03-09 04:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('listing_title', models.CharField(max_length=64)),
                ('item_price', models.CharField(max_length=16)),
                ('inventory_product_quantity', models.FloatField()),
                ('inventory_item_create_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('inventory_item_update_datetime', models.DateTimeField(auto_now=True)),
                ('inventory_available_from_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('item_picture', models.CharField(max_length=124)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItemAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=126)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('country', models.CharField(default='India', max_length=64)),
                ('postal_code', models.CharField(max_length=18)),
                ('latitude', models.FloatField(max_length=18)),
                ('longitude', models.FloatField(max_length=18)),
                ('item_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farmerapp.Inventory')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItemStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeasuringUnit',
            fields=[
                ('measuring_unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('measuring_unit', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=64, unique=True)),
                ('product_default_image', models.CharField(max_length=124)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.DecimalField(decimal_places=0, max_digits=9)),
                ('measuring_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerapp.MeasuringUnit')),
            ],
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.CharField(max_length=512)),
                ('address', models.CharField(max_length=126)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('country', models.CharField(default='India', max_length=64)),
                ('postal_code', models.CharField(max_length=18)),
                ('latitude', models.FloatField(default='12.9716', max_length=32)),
                ('longitude', models.FloatField(default='77.5946', max_length=32)),
                ('phone_primary', models.CharField(max_length=32, unique=True)),
                ('phone_verified', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('member_since', models.DateTimeField(default=django.utils.timezone.now)),
                ('registration_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerapp.RegistrationStatus')),
            ],
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='user_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerapp.UserStatus'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerapp.Users'),
        ),
        migrations.AddField(
            model_name='transporter',
            name='transporter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerapp.Users'),
        ),
        migrations.AddField(
            model_name='transporter',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerapp.Vehicle'),
        ),
        migrations.AddField(
            model_name='seller',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerapp.Users'),
        ),
        migrations.AddField(
            model_name='seller',
            name='sells',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerapp.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerapp.ProductCategory'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='inventory_item_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerapp.InventoryItemStatus'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerapp.Product'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerapp.ProductCategory'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product_measuring_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmerapp.MeasuringUnit'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerapp.Seller'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='buyer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerapp.Users'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='buys',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerapp.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='transporter',
            unique_together={('transporter_id', 'vehicle')},
        ),
        migrations.AlterUniqueTogether(
            name='seller',
            unique_together={('seller', 'sells')},
        ),
        migrations.AlterUniqueTogether(
            name='buyer',
            unique_together={('buyer_id', 'buys')},
        ),
    ]
