# Generated by Django 2.0.3 on 2019-03-31 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seller',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='seller',
            name='sells',
        ),
    ]
