# Generated by Django 2.0.3 on 2019-01-01 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0002_auto_20190101_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasuringUnit',
            fields=[
                ('measuring_unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('measuring_unit', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_measuring_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmerapp.MeasuringUnit'),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='measuring_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerapp.MeasuringUnit'),
        ),
        migrations.DeleteModel(
            name='ProductMeasuringUnit',
        ),
    ]
