# Generated by Django 2.0.3 on 2019-05-25 18:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0002_auto_20190331_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='NegotiationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.BigIntegerField()),
                ('sent_on', models.DateTimeField(default=datetime.datetime(2019, 5, 25, 18, 37, 4, 464029, tzinfo=utc))),
                ('accepted', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerapp.Buyer')),
                ('listing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerapp.Inventory')),
            ],
        ),
        migrations.CreateModel(
            name='TextTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.IntegerField()),
                ('template', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='negotiationrequest',
            name='request_body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerapp.TextTemplates'),
        ),
        migrations.AddField(
            model_name='negotiationrequest',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerapp.Seller'),
        ),
        migrations.AddField(
            model_name='negotiationrequest',
            name='sent_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerapp.Users'),
        ),
    ]
