# Generated by Django 2.0.3 on 2019-05-25 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0003_auto_20190525_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negotiationrequest',
            name='sent_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
