# Generated by Django 2.0.3 on 2019-05-25 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0004_auto_20190525_2038'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TextTemplates',
            new_name='TextTemplate',
        ),
    ]
