# Generated by Django 2.0.3 on 2019-05-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0005_auto_20190525_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negotiationrequest',
            name='request_body',
            field=models.TextField(),
        ),
    ]
