# Generated by Django 2.0.3 on 2019-05-26 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0006_auto_20190526_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negotiationrequest',
            name='sent_by',
        ),
    ]
