# Generated by Django 2.0.3 on 2019-05-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0007_remove_negotiationrequest_sent_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationrequest',
            name='sent_by',
            field=models.TextField(default='seller'),
            preserve_default=False,
        ),
    ]
