# Generated by Django 2.0.3 on 2019-05-29 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0009_auto_20190529_1842'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='negotiationrequest',
            unique_together={('listing_id', 'buyer')},
        ),
    ]
