# Generated by Django 2.0.3 on 2019-06-02 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0010_auto_20190529_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='NegotiationRequestStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='negotiationrequest',
            name='accepted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerapp.NegotiationRequestStatus'),
        ),
    ]
