# Generated by Django 2.0.3 on 2019-06-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0011_auto_20190602_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negotiationrequeststatus',
            name='status',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
