# Generated by Django 2.0.3 on 2019-06-14 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0012_auto_20190602_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='negotiationrequest',
            old_name='listing_id',
            new_name='listing',
        ),
        migrations.AlterUniqueTogether(
            name='negotiationrequest',
            unique_together={('listing', 'buyer')},
        ),
    ]
