# Generated by Django 2.0.3 on 2019-06-14 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0013_auto_20190614_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='negotiationrequest',
            old_name='listing',
            new_name='listing_id',
        ),
        migrations.AlterUniqueTogether(
            name='negotiationrequest',
            unique_together={('listing_id', 'buyer')},
        ),
    ]
